### ISSUE TITLE
Fix uninitialized constant Rzo::App::Subcommand::Pathname (NameError)

### ISSUE THREAD

**Issue by jeffmccune** [ghoneycutt/rizzo#14]
When installed as a normal gem:

```
rzo config
/Users/jeff/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rzo-0.3.0/lib/rzo/app/subcommand.rb:19:in `load_rizzo_config': uninitialized constant Rzo::App::Subcommand::Pathname (NameError)
        from /Users/jeff/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rzo-0.3.0/lib/rzo/app/subcommand.rb:157:in `load_rizzo_config'
        from /Users/jeff/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rzo-0.3.0/lib/rzo/app/subcommand.rb:57:in `load_config!'
        from /Users/jeff/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rzo-0.3.0/lib/rzo/app/config.rb:10:in `run'
        from /Users/jeff/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rzo-0.3.0/lib/rzo/app.rb:79:in `run'
        from /Users/jeff/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rzo-0.3.0/exe/rzo:6:in `<top (required)>'
        from /Users/jeff/.rbenv/versions/2.1.9/bin/rzo:23:in `load'
        from /Users/jeff/.rbenv/versions/2.1.9/bin/rzo:23:in `<main>'
```

**Comment by ghoneycutt** [comment]
Released in v0.4.0
